### ISSUE TITLE
Good solution exists :)

### ISSUE THREAD

**Issue by Madoshakalaka** [alanbacon/pipenv2setup#1]
Hi I accidentally found your project when checking pipenv-setup on pypi!

Good works! But I have to recommend the solution here:

https://github.com/Madoshakalaka/pipenv-setup

it's highly covered with tests on 3.6 3.7 3.8 across 3 operating systems. I'm actively maintaining it and it's gaining recognition.

I'd welcome any feature request or pull requests!!

**Comment by alanbacon** [comment]
Hello! Glad there are other people out there improving python packaging. Good to hear that it's fully tested, maintained and cross-platform.

I did come across your project before writing mine. What made me write mine anyway was the fact that your project (if I've understood correctly) syncs the `pipfile.lock` file not the `pipfile`. My project interprets the `pipfile` only.

I've always understood that the lock file is meant for creating a reproducible environment and it is overly restrictive to be directly mapped onto `setup.py`. 
i.e. It will not allow updates to dependencies, it also specifies all sub-dependancies, even though as a developer I should not be concerned what the sub-dependancies of my immediate dependancies are.

From https://packaging.python.org/discussions/install-requires-vs-requirements/:

> It is not considered best practice to use install_requires to pin dependencies to specific versions, or to specify sub-dependencies (i.e. dependencies of your dependencies). This is overly-restrictive, and prevents the user from gaining the benefit of dependency upgrades.

So my main feature request would be that you use the `pipfile` not the `pipfile.lock`.

**Comment by Madoshakalaka** [comment]
yeah...I know that paragraph too. You are making  point

**Comment by Madoshakalaka** [comment]
Hi! [pipenv-setup](https://github.com/Madoshakalaka/pipenv-setup) is massively improved now! Specifically, I incorporated your suggestion and `pipenv-setup sync --pipfile` now syncs Pipfile instead of the lockfile.

And a lot of work is done on compatibility. It now runs on python 2.7/3.4/3.5/3.6/3.7/3.8!
